language: java
sudo: false
jdk:
 - oraclejdk7
env:
  matrix:
  - TERM=dumb
install:
  - git clone https://github.com/stagemonitor/stagemonitor.git .stagemonitor
  - cd .stagemonitor
  - gradle compileJava installIntegrationSnapshot
script:
  - gradle test
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
