language: java
sudo: false
jdk:
 - openjdk6
 - oraclejdk7
 - openjdk7
 - oraclejdk8
env:
  matrix:
  - TERM=dumb
install:
  - git clone https://github.com/stagemonitor/stagemonitor.git .stagemonitor
  - pushd .stagemonitor
  - gradle test compileJava installIntegrationSnapshot
  - popd
script:
  - gradle test
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - .downloads
